"""Value objects for the identity bounded context."""

import uuid
from dataclasses import dataclass

from athlos.modules.identity.domain.exceptions import InvalidEmailError
from athlos.platform.domain.value_object import ValueObject


@dataclass(frozen=True)
class UserId(ValueObject):
    value: uuid.UUID

    @classmethod
    def generate(cls) -> "UserId":
        return cls(uuid.uuid4())


@dataclass(frozen=True)
class DeviceLinkId(ValueObject):
    """Identity of a `Device` aggregate - server-generated, distinct from
    `DeviceId` (see docs/DECISIONS.md: `device_id` alone cannot be the
    aggregate's identity, since the same physical device can be linked to
    several users).
    """

    value: uuid.UUID

    @classmethod
    def generate(cls) -> "DeviceLinkId":
        return cls(uuid.uuid4())


@dataclass(frozen=True)
class DeviceId(ValueObject):
    """A device identifier generated by the client (e.g. an installation
    UUID), not the server - no `.generate()` here, unlike `UserId`/
    `DeviceLinkId` (see docs/DECISIONS.md).
    """

    value: uuid.UUID


@dataclass(frozen=True)
class Email(ValueObject):
    """An email address, normalized and structurally validated.

    Validation is deliberately minimal (no external library): normalizes
    with `strip()` + `lower()` first, then checks for exactly one `@` with
    non-empty local and domain parts. Stricter validation (or a dedicated
    library) can be added later if real-world input demands it.
    """

    value: str

    def __post_init__(self) -> None:
        normalized = self.value.strip().lower()
        local, _, domain = normalized.partition("@")
        if not local or not domain or "@" in domain:
            raise InvalidEmailError(self.value)
        object.__setattr__(self, "value", normalized)


@dataclass(frozen=True)
class PasswordHash(ValueObject):
    """An already-hashed password.

    The domain never sees a raw password - only the application layer,
    via the `PasswordHasher` port, produces this value (see
    docs/DECISIONS.md). No validation here: the hash's shape is entirely
    owned by whichever algorithm produced it (infrastructure concern).
    """

    value: str
